### ISSUE TITLE
통합 테스트(프론트 + api) 모니터링용 설정 적용

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-server#125]
## 작업내용

- 배포 환경에서 기능 검증을 위해 API를 테스트 할 때, 추가 요구사항 외에도 이슈가 되는 부분이 있는지 확인하고자 적용
- #126 
- #127 

## 목차

1. 슬로우 쿼리 로그 활성화
1. 스프링부트 actuator 적용
1. 프로메테우스 & grafana 적용

---

## 1. 슬로우 쿼리 로그 활성화

- `my.cnf`에 슬로우 쿼리(`2초`) 로그 활성화 옵션 적용 

```bash
[mysqld]
# 슬로우 쿼리를 FILE로 출력
log_output = FILE
# 출력할 파일 위치를 설정
slow_query_log_file = /var/log/mysql/mysql-slow.log

# 슬로우 쿼리 활성화
slow_query_log = 1

# 아래 변수에 지정된 초(seconds)이상 쿼리가 수행되면 슬로우 쿼리에 기록
long_query_time = 2
```

```sql
mysql> SHOW VARIABLES WHERE 
    -> Variable_Name LIKE 'slow_query_log' OR 
    -> Variable_Name LIKE 'long_query_time' OR
    -> Variable_Name LIKE 'log_output';
+-----------------+----------+
| Variable_name   | Value    |
+-----------------+----------+
| log_output      | FILE     |
| long_query_time | 2.000000 |
| slow_query_log  | ON       |
+-----------------+----------+
3 rows in set (0.00 sec)
```

- 기능 정상 동작 테스트

```sql
# Time: 2022-07-17T20:37:27.320818Z
# User@Host: root[root] @ localhost []  Id:     2
# Query_time: 3.000273  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
SET timestamp=1658090247;
select sleep(3);
```

## 2. 스프링부트 actuator 적용

- `애플리케이션 상태 확인`을 위해 스프링부트 actuator 적용

```groovy
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
}
```

- actuator Endpoint를 `health`와 `prometheus`만 열어놓음
- `application.yml`

```yml
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
```

### 프로메테우스

- `spring actuator` endpoint로부터 데이터를 받을 수 있도록 `prometheus.yml` 수정

```yml
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
  
  #...

  - job_name: daangn_server_node
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8081','localhost:8881','localhost:9081']
```

![스크린샷 2022-07-18 오전 6 36 19](https://user-images.githubusercontent.com/75410527/179425624-e6dc4ed2-e226-4c85-9c33-b39ac1a12ef7.png)

### grafana

- Dashboard 템플릿으로는 `JVM (Micrometer)` 적용

![스크린샷 2022-07-18 오전 6 55 35](https://user-images.githubusercontent.com/75410527/179426251-0ac071e6-6be0-4dc3-abf7-b0b47c441c5c.png)

---

- 참고
  - [[MySQL] 성능 개선을 위한 프로파일링 1편: 슬로우 쿼리 로그](https://velog.io/@breadkingdom/MySQL-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0%EC%9D%84-%EC%9C%84%ED%95%9C-%ED%94%84%EB%A1%9C%ED%8C%8C%EC%9D%BC%EB%A7%81-1)
  - [AWS를 활용한 slowquery 모니터링 및 관리](https://imweb.me/blog?idx=72)
  - [프로메테우스, 그라파나를 이용한 스프링부트 모니터링](https://covenant.tistory.com/244)
  - [Prometheus + Grafana 적용기](https://velog.io/@betalabs/Prometheus-Grafana-%EC%A0%81%EC%9A%A9%EA%B8%B0#5-prometheus-%EC%84%A4%EC%A0%95)
