### ISSUE TITLE
Spring Boot 로그 모니터링 적용 (서버 외부에 로그를 쌓는 법)

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-server#129]
### 수정 후

- Spring Boot 로그 모니터링으로 `Grafana Loki` 적용

### 수정 전

- 기존에 컨테이너 내부에 Spring Boot 로그를 쌓는 식으로 적용해놨었음

### 작업 계기

- 통합 테스트를 위해 aws 서버를 띄워놨더니 외부에서 많은 트래픽 발생으로 서버가 죽었음
- 로그는 쌓여 있었지만 서버가 죽어서 컨테이너가 내려감에 따라 내부 로그 확인이 불가능했음
- 그래서 `도커 볼륨`을 사용해서 컨테이너 내부에 생성되는 로그를 호스트로 옮겼고, 또한 이 로그를 외부에서 모니터링하고자 `grafana loki` 적용

### docker-volume 적용

- `docker-compose blue/green`에 volume 옵션 적용

```yml
version: "3"

services:
  api_server:
    #...
    volumes:
      - /tmp/log:/app/log
  chat_server:
    #...
    volumes:
      - /tmp/log:/app/log
  noti_server:
    #...
    volumes:
      - /tmp/log:/app/log

```

### docker-volume 경로에 맞게 logback 수정

```xml
<appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <!-- 기록할 파일명과 경로를 설정 -->
    <file>log/api-debug.log</file>

<appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <!-- 기록할 파일명과 경로를 설정 -->
    <file>log/chat-debug.log</file>

<appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <!-- 기록할 파일명과 경로를 설정 -->
    <file>log/noti-debug.log</file>
```

###  grafana loki 적용

- 해당 내용은 아래 URL에 자세히 정리
  - [Grafana Loki 적용기](https://cotchan.github.io/todayilearned/2022/07/19/til-grafana-loki.html)

## 결과

- 아래와 같은 형태로 `api-server`, `chat-server`, `notification-server`에서 발생하는 로그 수집

![스크린샷 2022-07-19 오후 3 17 50](https://user-images.githubusercontent.com/75410527/179692902-a2ec922c-4fa2-4694-8f40-0ed578846bcf.png)
