### ISSUE TITLE
server 레포와 client 레포 별도 배포 시 동기화를 위한 networks 옵션 적용

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-server#72]
## 고민사항

- 현재 daangn-daangn 프로젝트는 daangn-server, daangn-client 두 레포로 분리되어 관리
- 레포지토리 별로 배포를 진행한다고 했을 때 예상 배포 형상
  - daangn-server: api-server, chat-server, zookeeper, kafka
  - daangn-client: nginx(80) + react-nginx(3000)
- 문제: daangn-client 배포 시 리버스 프록시를 제공하는 80번포트 nginx에서 daangn-server의 서비스를 식별할 수 있어야함

**Comment by cotchan** [comment]
## Docker container 간 네트워크 통신

- 도커 컴포즈 없이 서로 다른 레포에서 배포하는 컨테이너끼리 통신할 수 있는지 확인해본 내용입니다. 

---

### 목차

1. [Docker container 간 네트워크 통신 방법](#docker-container-간-네트워크-통신-방법)
    - [도커 네트워크 만들기](#도커-네트워크-만들기)
    - [parent 컨테이너 실행 시 --network 옵션 및 parent 컨테이너의 이름 부여](#parent-컨테이너-실행-시---network-옵션-및-parent-컨테이너의-이름-부여)
    - [child 컨테이너 실행 시 --network 옵션 및 parent 컨테이너 식별하기](#child-컨테이너-실행-시---network-옵션-및-parent-컨테이너-식별하기)
1. [Networking in Compose](#networking-in-compose)
    - [Configure the default network](#configure-the-default-network)
    - [외부 네트워크 사용(Use a pre-existing network)](#외부-네트워크-사용use-a-pre-existing-network)
1. [네트워크 통신 구체적인 예시(중요)](#네트워크-통신-구체적인-예시중요)
    - [검증하려고 했던 내용](#검증하려고-했던-내용)
    - [docker-compose.yml(daangn-server)](#docker-composeymldaangn-server)
    - [Dockerfile(nginx)](#dockerfilenginx)
    - [docker build nginx Dockerfile](#docker-build-nginx-dockerfile)
    - [docker network inspect daangn_net](#docker-network-inspect-daangn_net)

---

### Docker container 간 네트워크 통신 방법

#### 도커 네트워크 만들기

```bash
# $ docker network create {your_network}
$ docker network create daangn_net
```

#### parent 컨테이너 실행 시 --network 옵션 및 parent 컨테이너의 이름 부여

- `parent`라는 단어가 나온 이유는 client-server 구조의 네트워킹을 가정할 때 server쪽에 해당하는 컨테이너가 parent입니다.
  - 이 컨테이너가 먼저 떠있어야 client container 쪽에서 server container를 식별하고 붙을 수 있습니다.
- 이 [daangn-server의 docker-compose.yml](#docker-composeymldaangn-server)을 참고하면 됩니다.

#### child 컨테이너 실행 시 --network 옵션 및 parent 컨테이너 식별하기

- child 컨테이너도 `network` 옵션을 주고 띄워야 합니다.

```bash
# 도커를 처음 만들 때 정의한 브릿지에 연결하는 방법
# $ docker run --netowrk {your_bridge} {docker_image}
$ docker run -p 80:80 --network daangn_net zhtcks/nginx
```

---

### Networking in Compose

- `디폴트 네트워크` 안에서 컨테이너간 통신은 `서비스 이름이 호스트명으로 사용`됩니다.

#### Configure the default network

- 자체 네트워크를 지정하는 대신 아래에 항목을 정의하여 앱 전체의 기본 네트워크 설정을 변경할 수도 있습니다.
- 외부 네트워크와의 차이는 이 옵션의 경우 docker-compose가 내려가면 해당 네트워크도 같이 내려갑니다.
  - 이 때는 `driver` 옵션을 사용합니다.

```yml
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres

networks:
  default:
    # Use a custom driver
    driver: custom-driver-1
```

#### 외부 네트워크 사용(Use a pre-existing network)

- 컨테이너간 네트워크에 이미 정의한 네트워크를 사용한다면 `external` 옵션으로 정의합니다. 

```yml
services:
  # ...
networks:
  default:
    external:
      name: my-pre-existing-network
```

---

### 네트워크 통신 구체적인 예시(중요)

#### 검증하려고 했던 내용

- `daangn-server`를 docker-compose로 단독 배포
- `80번 포트 nignx 컨테이너`는 당근 클라이언트 레포에서 배포한다고 가정하고 두 레포 컨테이너를 연결하기

#### docker-compose.yml(daangn-server)

- 핵심은 두 가지입니다.
  - `container_name`을 반드시 지정
  - `networks.default.external.name` 속성에 기존에 만든 네트워크 설정을 추가해줍니다.

```yml
version: "3"

services:
  api_server:
    container_name: apiapi

  chat_server:
    container_name: chatchat

networks:
  default:
    external:
      name: daangn_net
```

#### Dockerfile(nginx)

- `default.conf`

```
upstream api {
    # 여기에 같은 네트워크 안에 있는 컨테이너 이름을 써야하는 게 매우 중요한 내용입니다.
    # server {your_API_container_id}:{PORT}; 이렇게 기입해도 똑같이 동작합니다. 
    server apiapi:8080;
}

upstream chat {
    server chatchat:8880;
}

server {
    listen 80;

    # '/' 경로로 시작하는 모든 요청은 http://frontend로 보냅니다.
    location /api {
        proxy_pass http://api;
    }

    # '/api/' 경로로 시작하는 요청은 http://backend로 보냅니다.
    location /chat {
        proxy_pass http://chat;
    }
}
```

- 참고했던 샘플
  - 출처: https://81shinez.tistory.com/7 

```
upstream {your_resolver_name} {
	server {your_API_container_id}:{PORT};
}

server {
    location /api {
    	proxy_pass http://{your_resolver_name}$request_uri
    }
}
```

#### docker build nginx Dockerfile

- 컴포즈는 그냥 docker-compose up으로 실행하면 됩니다.
- Dockerfile도 `--network` 옵션을 줘서 컴포즈에 정의한 네트워크와 같은 네트워크로 붙도록 합니다.

```bash
$ docker build -t zhtcks/nginx ./
$ docker run -p 80:80 --network daangn_net zhtcks/nginx
```

#### docker network inspect daangn_net

```bash
$ docker network inspect daangn_net
```

- `daangn_net` 네트워크 안에 80번 포트 nginx 컨테이너와 daangn_server 컨테이너가 모두 있는 걸 확인할 수 있습니다.

```yml
[
    {
        "Name": "daangn_net",
        "Id": "974c4b4effd9b0220a5984160fb7aaa52a8f51eff58ce95f9395aa2554b5c289",
        "Created": "2022-05-07T23:15:49.2895195Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.26.0.0/16",
                    "Gateway": "172.26.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4677f53f15f94f253c847676503890fa6091348816b2ecd439c7b53f0933afc5": {
                "Name": "apiapi",
                "EndpointID": "9b46adc870bbc02522fffc7e9625821e7a02e8c770608832c8e7970ef46bab44",
                "MacAddress": "02:42:ac:1a:00:02",
                "IPv4Address": "172.26.0.2/16",
                "IPv6Address": ""
            },
            "ad3d39717dedab780360d0b8b3df8d23495f1eb9e492410d79d76b8cd60b52b6": {
                "Name": "zealous_galileo",
                "EndpointID": "95f1dab901b34fba0a17fb303ff978cdff1617f1f3c35b94f5e324e880dec4d5",
                "MacAddress": "02:42:ac:1a:00:04",
                "IPv4Address": "172.26.0.4/16",
                "IPv6Address": ""
            },
            "ad4a12eb814dbb2fc9418a763cbc829d6f01241ab63634930ad1d096325c1396": {
                "Name": "chatchat",
                "EndpointID": "04858d21bef0f098ab2f7bdaac5c8e04852be81adb347fd29ff92a880334947d",
                "MacAddress": "02:42:ac:1a:00:03",
                "IPv4Address": "172.26.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

---

- 참고
  - [Nginx 도커 컨테이너에서 Reverse Porxy를 활용해 도커 API컨테이너와 통신하기](https://81shinez.tistory.com/7) 
  - [Docker Compose 네트워크](https://www.daleseo.com/docker-compose-networks/#%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EA%B0%84-%ED%86%B5%EC%8B%A0)
  - [Networking in Compose](https://docs.docker.com/compose/networking/#configure-the-default-network)
  - [컨테이너 간 통신](https://cornswrold.tistory.com/500)
