### ISSUE TITLE
multi-datasource Bean으로 전환

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-server#73]
## 작업 사유

- 프로젝트 내 `mysql`, `mongodb`를 사용하면서 각 각의 DB를 핸들링하는 `transactionManager` 정의 필요
- 또한 mongodb의 경우 `multi document transaction`을 위해서는 `transactionManager` 선언이 필수

**Comment by cotchan** [comment]
## JavaConfig로 Datasource 설정하기

- 관계형 DB에 대해 JavaConfig를 사용해서 Datasource 빈을 정의하는 방법에 대해 정리
- 연결해야할 datasource 가 여러개일 경우, 아래의 과정을 따라 프로퍼티를 별도로 설정하고, JavaConfig 파일을 설정

---

### 목차

1. [프로퍼티 설정으로 dataSource 빈 자동 생성](#프로퍼티-설정으로-datasource-빈-자동-생성)
    - [DB 연결에 관한 예약된 Key](#db-연결에-관한-예약된-key)
    - [JPA 설정에 관한 예약된 Key](#jpa-설정에-관한-예약된-key)
1. [JavaConfig에 application.yml 설정값 주입하여 dataSource 빈 직접 생성](#javaconfig에-applicationyml-설정값-주입하여-datasource-빈-직접-생성)
    - [수정사항1](#수정사항1)
    - [수정사항2](#수정사항2)
    - [수정사항3(CamelCase에서 SnakeCase 변환)](#수정사항3camelcase에서-snakecase-변환)
1. [JavaConfig 설정](#javaconfig-설정)
    - [@EnableJpaRepositories](#enablejparepositories)
    - [DataSource와 JpaProperties](#datasource와-jpaproperties)
    - [LocalContainerEntityManagerFactoryBean](#localcontainerentitymanagerfactorybean)
    - [PlatformTransactionManager](#platformtransactionmanager)

---

### 프로퍼티 설정으로 dataSource 빈 자동 생성

- JavaConfig 클래스로 dataSource 빈 생성을 하지 않아도 `예약된 키로 프로퍼티 설정을 하면` 자동으로 jpa 설정과 dataSource 빈을 생성해줍니다.

```yml
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;
      jdbc-url: jdbc:h2:tcp://localhost/~/daangn;MODE=MYSQL;
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
```

#### DB 연결에 관한 예약된 Key

- DB 연결에 관한 예약된 Key는 `spring.datasource`입니다.
- `driver-class-name`, `url`, `username`, `password` 속성을 반드시 설정해야 합니다.
- DBCP Pool은 tomcat, dbcp2, hikari가 있으며, 사용할 DBCP Pool 를 하나 설정해주면 됩니다.

#### JPA 설정에 관한 예약된 Key

- JPA 설정에 관한 예약된 Key는 `spring.jpa`입니다.
- jpa 설정은 설정하지 않을 시, 기본 값으로 대체되므로 필수적으로 설정할 필요는 없습니다.
- 테이블명 생성 규칙, 컬럼명 생성규칙, ddl 생성 방식, sql beautify 등 여러 편의 설정을 지정할 수 있습니다.
- 이름 생성 규칙은 spring.jpa.hibernate.naming.implicit-strategy, spring.jpa.hibernate.naming.physical-strategy에 설정할 수도 있으나, @ConfigurationProperties를 통해 프로퍼티를 로딩할 때 불러올 수 없기 때문에 위와 같이 spring.jpa.properties.hibernate 내에 설정하는 것을 권장합니다.

---

### JavaConfig에 application.yml 설정값 주입하여 dataSource 빈 직접 생성

- 프로퍼티의 예약된 key에 datasource 설정을 하고 웹 애플리케이션을 실행하면 dataSource 빈이 자동으로 생성됩니다.
- 웹 애플리케이션 상에서 이용할 database 정보가 하나라면 프로퍼티 자동 설정을 이용하는 것이 편리해서 좋습니다. 
  - 하지만 여러개의 database를 연결해야 할 경우에는 JavaConfig 또는 xml을 통한 datasource 설정이 필요합니다.

#### 프로퍼티 수정

- JavaConfig 설정으로 프로퍼티 값을 읽으려면 `2가지 설정을 수정`해야 합니다.

#### 수정사항1

- spring.datasource에 설정되어있었던 driver-class-name, url, username, password를 `hikari 내부로 옮깁니다.`
- JavaConfig에서 `@ConfigurationProperties`로 dataSource 정보를 읽어들일 때, 트리형태로 datasource 하위 키인 `hikari`를 읽어들이지 않고, 같은 키 레벨에 설정된 곳에서 `database url`, `driver-class-name`, `username`, `password` 및 기타 정보를 읽어들입니다.

```java
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      # jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;
      jdbc-url: jdbc:h2:tcp://localhost/~/daangn;MODE=MYSQL;
      username: sa
      password:
```

#### 수정사항2

- 또한 hikariCP 는 database url을 jdbc-url이라는 예약된 키로 받기 때문에 url을 `jdbc-url로 변경합니다.`

#### 수정사항3(CamelCase에서 SnakeCase 변환)

- 프로퍼티 설정으로 dataSource 빈 생성 시 `CamelCase`에서 `SnakeCase`로 자동으로 변환해줬습니다.
- 하지만 JavaConfig 설정으로 아래 설정을 추가해줘야 CamelCase에서 SnakeCase로 변환이 됩니다.
- 위의 수정사항1,2 보단 중요도가 많이 떨어지지만 막상 까먹고 있으면 빡치는 포인트이기에 정리해놓습니다.

```yml
spring:
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
```

#### JavaConfig 설정

```java
package com.daangndaangn.common.configure;

import org.springframework.boot.autoconfigure.orm.jpa.JpaProperties;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.transaction.PlatformTransactionManager;

import javax.sql.DataSource;

@Configuration // Configuration 클래스임을 명시
@EnableJpaRepositories(
    basePackages = "com.daangndaangn.common.api.repository", // 해당 DataSource를 적용할 패키지 경로, 해당 패키지가 적용될 repository
    entityManagerFactoryRef = "apiEntityManager",            // 해당 TransactionEntityManagerFactory가 사용할 메소드명
    transactionManagerRef = "apiTransactionManager"          // 해당 TransactinoManager가 참조할 메소드 명
)
public class ApiDbConfigure {

    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.hikari")
    public DataSource apiDataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean
    @ConfigurationProperties(prefix = "spring.jpa")
    public JpaProperties jpaProperties() {
        return new JpaProperties();
    }

    @Bean
    public LocalContainerEntityManagerFactoryBean apiEntityManager(EntityManagerFactoryBuilder builder,
                                                                   DataSource dataSource,
                                                                   JpaProperties jpaProperties) {
        return builder
                .dataSource(dataSource)
                .properties(jpaProperties.getProperties())
                .packages("com.daangndaangn.common.api.entity")
                .persistenceUnit("default")
                .build();
    }

    @Primary
    @Bean(name = "apiTransactionManager")
    public PlatformTransactionManager apiTransactionManager(LocalContainerEntityManagerFactoryBean entityManagerFactory) {
        JpaTransactionManager transactionManager = new JpaTransactionManager(entityManagerFactory.getObject());
        return transactionManager;
    }
}
```

#### @EnableJpaRepositories

- multiple datasource 설정 시, `연동시킬 repositories 패키지`와 entityManagerFactoryRef, transactionManagerRef를 설정하는 부분입니다.

#### DataSource와 JpaProperties

- `spring.datasource.hikari에 설정한 구성 정보`를 가져와 `dataSource 빈을 구성`합니다.
- `spring.jpa에 설정한 jpa 관련 설정`을 읽어들여 `jpa 설정`을 합니다.

```java
@Bean
@ConfigurationProperties(prefix = "spring.datasource.hikari")
public DataSource apiDataSource() {
    return DataSourceBuilder.create().build();
}

@Bean
@ConfigurationProperties(prefix = "spring.jpa")
public JpaProperties jpaProperties() {
    return new JpaProperties();
}
```

#### LocalContainerEntityManagerFactoryBean

- 위에 설정했던 `dataSource`, `jpaProperties` 설정을 가져와 `엔티티매니저를 만드는 entityManagerFactory 빈을 만듭니다.`

```java
@Bean
public LocalContainerEntityManagerFactoryBean apiEntityManager(EntityManagerFactoryBuilder builder,
                                                               DataSource dataSource,
                                                               JpaProperties jpaProperties) {

    return builder
            .dataSource(dataSource)
            .properties(jpaProperties.getProperties())
            .packages("com.daangndaangn.common.api.entity")
            .persistenceUnit("default")
            .build();
}
```

#### PlatformTransactionManager

- 위에 설정한 entityManagerFactory를 이용하여 `트랜젝션 처리에 이용되는 transactionManager 빈을 만듭니다.`

```java
@Bean(name = "apiTransactionManager")
public PlatformTransactionManager apiTransactionManager(LocalContainerEntityManagerFactoryBean entityManagerFactory) {
    JpaTransactionManager transactionManager = new JpaTransactionManager(entityManagerFactory.getObject());
    return transactionManager;
}
```

---

- 출처
  - [[Spring Boot] JavaConfig로 Datasource 설정하기](https://blog.jiniworld.me/69) 
  - [Spring Boot 1개에 DB 2개 연결?](https://wooki92.tistory.com/m/12)
  - [Spring JPA – Multiple Databases](https://www.baeldung.com/spring-data-jpa-multiple-databases)
