### ISSUE TITLE
daangn-server 무중단 배포 적용

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-server#96]
## 작업 내용

- PR: #92 
- daangn-daangn 프로젝트를 무중단 배포할 수 있도록 `daangn-server`에 `blue/green` 방식 무중단 배포 적용
- 여기서 정의한 무중단 배포 방식은 1대의 서버 내에서 `nginx reload`를 사용하여 `blue/green` 인스턴스 반환 

### 목차

1. ci에 git-action 적용
1. appspec.yml
1. deploy.sh
1. docker-compose-prod.blue.yml & docker-compose-prod.green.yml
1. 참고 레퍼런스

---

## 1. ci에 git-action 적용

- `git-action` 역할
  - `gradle build` 후 프로젝트 파일 압축하여 S3로 전송 및 CodeDeploy Run

```yml
# .github/workflows/deploy.yml
name: daangn-server

on:
  workflow_dispatch: # 수동으로 해당 workflow를 실행시키겠다는 뜻

env: # 현재 스크립트에서 사용할 환경변수 정의
  S3_BUCKET_NAME: cotchan-service-deploy
  PROJECT_NAME: daangn-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # 깃헙이 제공하는 워크스페이스 (이 workflow 를 실행하는 공간) 에서 내 저장소가 위치한 곳으로 이동
        uses: actions/checkout@v3

      - name: create env file # 깃헙 settings > secrets 에 올려놓은 비밀 값을 복사해 .env 파일로 생성
        run: |
          touch .env
          echo "${{ secrets.ENV_PROD_VARS }}" >> .env

      - name: Set up JDK 11 # java 셋업
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Grant execute permission for gradlew # gradlew에 실행권한
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle # 프로젝트 build
        run: ./gradlew clean build -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name sandbox-service-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name sandbox --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
```

---

## 2. appspec.yml

- Code Deploy Agent가 배포완료 시 아래 yml에 정의한대로 빌드 스크립트 실행

```yml
version: 0.0
os: linux
files:
  - source: / # 현재 프로젝트의 루트 경로
    destination: /home/ubuntu/daangn-server/ # S3에서 받아올 프로젝트의 위치를 지정 (EC2 내부의 어떤 디렉토리에 전달 ?)
    overwrite: yes # 덮어쓰기 할 것인지?

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks: # CodeDeploy의 배포에는 각 단계 별 수명 주기가 있는데, 수명 주기에 따라 원하는 스크립트를 수행가능
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ubuntu
```

---

## 3. deploy.sh

- `docker-compose`를 사용하여 `blue/green` 배포 방식을 적용

```bash
#!/bin/bash

SOURCE_REPOSITORY=/home/ubuntu/daangn-server
DOCKER_APP_NAME=daangn-server # DOCKER_APP_NAME에는 프로젝트명을 적는다.

# Blue 를 기준으로 현재 떠있는 컨테이너를 한다.
EXIST_BLUE=$(docker-compose -p ${DOCKER_APP_NAME}-blue -f ${SOURCE_REPOSITORY}/docker-compose-prod.blue.yml ps | grep Up)

# 컨테이너 스위칭
if [ -z "$EXIST_BLUE" ]; then
    echo "blue up"
    docker-compose -p ${DOCKER_APP_NAME}-blue -f ${SOURCE_REPOSITORY}/docker-compose-prod.blue.yml up --build -d
    BEFORE_COMPOSE_COLOR="green"
    AFTER_COMPOSE_COLOR="blue"
else
    echo "green up"
    docker-compose -p ${DOCKER_APP_NAME}-green -f ${SOURCE_REPOSITORY}/docker-compose-prod.green.yml up --build -d
    BEFORE_COMPOSE_COLOR="blue"
    AFTER_COMPOSE_COLOR="green"
fi

sleep 10

# 새로운 컨테이너가 제대로 떴는지 확인
EXIST_AFTER=$(docker-compose -p ${DOCKER_APP_NAME}-${AFTER_COMPOSE_COLOR} -f ${SOURCE_REPOSITORY}/docker-compose-prod.${AFTER_COMPOSE_COLOR}.yml ps | grep Up)
if [ -n "$EXIST_AFTER" ]; then
    echo "nginx reload.."
    # nginx.config를 컨테이너에 맞게 변경해주고 reload 한다
    sudo cp ${SOURCE_REPOSITORY}/nginx/service-url-${AFTER_COMPOSE_COLOR}.inc /etc/nginx/conf.d/backend-url.inc
    sudo systemctl reload nginx

    # 이전 컨테이너 종료
    echo "$BEFORE_COMPOSE_COLOR down"
    docker-compose -p ${DOCKER_APP_NAME}-${BEFORE_COMPOSE_COLOR} -f ${SOURCE_REPOSITORY}/docker-compose-prod.${BEFORE_COMPOSE_COLOR}.yml down
fi
```

---

## 4. docker-compose-prod.blue.yml & docker-compose-prod.green.yml

- blue & green 배포를 위해 docker-compose.yml 파일 2개 정의
- 두 파일은 외부에 개방하는 포트정보만 다를 뿐 나머지 정보는 동일

docker-compose-prod.blue.yml

```yml
version: "3"

# 두 docker-compose.yml 모두 포트만 다를 뿐 띄우는 컨테이너 정보는 동일
services:
  api_server:
    container_name: daangn-api-server-blue
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
  chat_server:
    container_name: daangn-chat-server-blue
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    ports:
      - "8881:8880"
    env_file:
      - .env
  noti_server:
    container_name: daangn-notification-server-blue
    build:
      context: ./noti-server
      dockerfile: Dockerfile
    ports:
      - "9081:9080"
    env_file:
      - .env

networks:
  default:
    external:
      name: daangn_net
```

docker-compose-prod.green.yml

```yml
version: "3"

# 두 docker-compose.yml 모두 포트만 다를 뿐 띄우는 컨테이너 정보는 동일
services:
  api_server:
    container_name: daangn-api-server-green
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env
  chat_server:
    container_name: daangn-chat-server-green
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    ports:
      - "8882:8880"
    env_file:
      - .env
  noti_server:
    container_name: daangn-notification-server-green
    build:
      context: ./noti-server
      dockerfile: Dockerfile
    ports:
      - "9082:9080"
    env_file:
      - .env

networks:
  default:
    external:
      name: daangn_net
```

---

## 5. 참고 레퍼런스

  - [Github Actions + CodeDeploy + Nginx 로 무중단 배포하기 (1)](https://wbluke.tistory.com/39)
  - [Github Actions + CodeDeploy + Nginx 로 무중단 배포하기 (2)](https://wbluke.tistory.com/40)
  - [Github Actions + CodeDeploy + Nginx 로 무중단 배포하기 (3)](https://wbluke.tistory.com/41)
  - [[AWS] Spring Boot,Travis CI, CodeDeploy, Nginx로 무중단 배포하기](https://devlog-wjdrbs96.tistory.com/309)
  - [[AWS] Spring Boot, Nginx, Docker 로 무중단 배포하기 - 1탄](https://devlog-wjdrbs96.tistory.com/316)
  - [[AWS] Spring, Nginx, Docker로 무중단 배포하기 - 2탄](https://devlog-wjdrbs96.tistory.com/317)
  - [docker-compose 무중단 배포 1편 (blue, green)](https://jay-ji.tistory.com/m/99)
  - [spring boot, docker, docker-copmpose, nginx 이용해서 무중단 배포하기](https://kukekyakya.tistory.com/entry/spring-boot-docker-docker-compose-nginx-%EC%9D%B4%EC%9A%A9%ED%95%B4%EC%84%9C-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0)
  - [[Docker] Docker Compose 프로젝트 무중단 배포](https://ozofweird.tistory.com/entry/Docker-Docker-Compose-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC)
